DELETE http://localhost:3003/api/blogs/6047bf942d56741d847c97f1
###
DELETE http://localhost:3003/api/blogs/60a74a763fd7901368ef6160
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImvDpHl0dMOkasOkMSIsImlkIjoiNjBhNTc2YzJmM2FmMTgxNGY0NmIyZTA5IiwiaWF0IjoxNjIxOTc5MjI1LCJleHAiOjE2MjE5ODI4MjV9.7WAIX4fh6BtA8lrLS0xJUwhfvNBkX47dsCQMgAce1_s
###
DELETE http://localhost:3003/api/blogs/60a74909d33a990af8c41c00
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImvDpHl0dMOkasOkMiIsImlkIjoiNjBhNWQzNTlhNDQ1NWQzYmI4ODU1ZjNhIiwiaWF0IjoxNjIxOTgwMjk5LCJleHAiOjE2MjE5ODM4OTl9.74usZ8bY-DLs-tcBF7FbBBMTqcC3VimgxTeMXdG1fyU